[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
healthcheckPath = "/"
healthcheckTimeout = 100 